-- 商户信息表
CREATE TABLE IF NOT EXISTS `merchant_info` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '商户编号',
  `name` varchar(128) NOT NULL COMMENT '商户名称',
  `logo` varchar(512) DEFAULT NULL COMMENT '商户logo',
  `contact_name` varchar(64) NOT NULL COMMENT '联系人',
  `contact_phone` varchar(20) NOT NULL COMMENT '联系电话',
  `license_no` varchar(64) NOT NULL COMMENT '营业执照号',
  `license_url` varchar(512) NOT NULL COMMENT '营业执照图片URL',
  `legal_person_name` varchar(64) NOT NULL COMMENT '法人姓名',
  `legal_person_id_card` varchar(32) NOT NULL COMMENT '法人身份证号',
  `legal_person_id_card_front_url` varchar(512) NOT NULL COMMENT '法人身份证正面图片URL',
  `legal_person_id_card_back_url` varchar(512) NOT NULL COMMENT '法人身份证反面图片URL',
  `bank_account_name` varchar(128) NOT NULL COMMENT '结算银行账户名',
  `bank_account_no` varchar(64) NOT NULL COMMENT '结算银行账号',
  `bank_name` varchar(128) NOT NULL COMMENT '开户行',
  `business_category` varchar(128) NOT NULL COMMENT '经营类目',
  `status` tinyint NOT NULL DEFAULT 0 COMMENT '商户状态：0-待审核 1-审核通过 2-审核拒绝 3-已禁用',
  `reject_reason` varchar(512) DEFAULT NULL COMMENT '审核拒绝原因',
  `audit_time` datetime DEFAULT NULL COMMENT '审核时间',
  `wx_sub_mch_id` varchar(64) DEFAULT NULL COMMENT '微信支付子商户号',
  `wx_applyment_id` varchar(64) DEFAULT NULL COMMENT '微信支付进件申请单号',
  `wx_applyment_status` varchar(32) DEFAULT NULL COMMENT '微信支付进件状态',
  `mini_app_qr_code_url` varchar(512) DEFAULT NULL COMMENT '小程序码URL',
  `douyin_access_token` varchar(256) DEFAULT NULL COMMENT '抖音授权access_token',
  `douyin_refresh_token` varchar(256) DEFAULT NULL COMMENT '抖音授权refresh_token',
  `douyin_open_id` varchar(128) DEFAULT NULL COMMENT '抖音授权openid',
  `douyin_token_expire_time` datetime DEFAULT NULL COMMENT '抖音授权过期时间',
  `user_id` bigint NOT NULL COMMENT '关联用户编号',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_tenant_id` (`tenant_id`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商户信息表';
