-- 微信公众号模块表结构
-- 根据 yudao-module-mp 实体类生成

CREATE TABLE IF NOT EXISTS `mp_account` (
    `id`          bigint       NOT NULL AUTO_INCREMENT COMMENT '编号',
    `name`        varchar(64)  NOT NULL DEFAULT '' COMMENT '公众号名称',
    `account`     varchar(64)  NOT NULL DEFAULT '' COMMENT '公众号账号',
    `app_id`      varchar(64)  NOT NULL DEFAULT '' COMMENT '公众号 appid',
    `app_secret`  varchar(128) NOT NULL DEFAULT '' COMMENT '公众号密钥',
    `token`       varchar(128)          DEFAULT '' COMMENT '公众号token',
    `aes_key`     varchar(128)          DEFAULT '' COMMENT '消息加解密密钥',
    `qr_code_url` varchar(512)          DEFAULT '' COMMENT '二维码图片URL',
    `remark`      varchar(256)          DEFAULT '' COMMENT '备注',
    `tenant_id`   bigint       NOT NULL DEFAULT 0 COMMENT '租户编号',
    `creator`     varchar(64)           DEFAULT '' COMMENT '创建者',
    `create_time` datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater`     varchar(64)           DEFAULT '' COMMENT '更新者',
    `update_time` datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted`     bit(1)       NOT NULL DEFAULT 0 COMMENT '是否删除',
    PRIMARY KEY (`id`)
) ENGINE = InnoDB COMMENT = '公众号账号';

CREATE TABLE IF NOT EXISTS `mp_user` (
    `id`               bigint       NOT NULL AUTO_INCREMENT COMMENT '编号',
    `openid`           varchar(64)  NOT NULL DEFAULT '' COMMENT '粉丝标识',
    `union_id`         varchar(64)           DEFAULT '' COMMENT '微信生态唯一标识',
    `subscribe_status` tinyint      NOT NULL DEFAULT 1 COMMENT '关注状态',
    `subscribe_time`   datetime              DEFAULT NULL COMMENT '关注时间',
    `unsubscribe_time` datetime              DEFAULT NULL COMMENT '取消关注时间',
    `nickname`         varchar(64)           DEFAULT '' COMMENT '昵称',
    `head_image_url`   varchar(512)          DEFAULT '' COMMENT '头像地址',
    `language`         varchar(32)           DEFAULT '' COMMENT '语言',
    `country`          varchar(64)           DEFAULT '' COMMENT '国家',
    `province`         varchar(64)           DEFAULT '' COMMENT '省份',
    `city`             varchar(64)           DEFAULT '' COMMENT '城市',
    `remark`           varchar(256)          DEFAULT '' COMMENT '备注',
    `tag_ids`          varchar(512)          DEFAULT '[]' COMMENT '标签编号数组',
    `account_id`       bigint       NOT NULL DEFAULT 0 COMMENT '公众号账号编号',
    `app_id`           varchar(64)  NOT NULL DEFAULT '' COMMENT '公众号 appId',
    `creator`          varchar(64)           DEFAULT '' COMMENT '创建者',
    `create_time`      datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater`          varchar(64)           DEFAULT '' COMMENT '更新者',
    `update_time`      datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted`          bit(1)       NOT NULL DEFAULT 0 COMMENT '是否删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_openid_app_id` (`openid`, `app_id`)
) ENGINE = InnoDB COMMENT = '公众号粉丝';

CREATE TABLE IF NOT EXISTS `mp_tag` (
    `id`          bigint      NOT NULL AUTO_INCREMENT COMMENT '主键',
    `tag_id`      bigint      NOT NULL COMMENT '公众号标签 id',
    `name`        varchar(64) NOT NULL DEFAULT '' COMMENT '标签名',
    `count`       int                  DEFAULT 0 COMMENT '此标签下粉丝数',
    `account_id`  bigint      NOT NULL DEFAULT 0 COMMENT '公众号账号编号',
    `app_id`      varchar(64) NOT NULL DEFAULT '' COMMENT '公众号 appId',
    `creator`     varchar(64)          DEFAULT '' COMMENT '创建者',
    `create_time` datetime    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater`     varchar(64)          DEFAULT '' COMMENT '更新者',
    `update_time` datetime    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted`     bit(1)      NOT NULL DEFAULT 0 COMMENT '是否删除',
    PRIMARY KEY (`id`)
) ENGINE = InnoDB COMMENT = '公众号标签';

CREATE TABLE IF NOT EXISTS `mp_menu` (
    `id`                   bigint       NOT NULL AUTO_INCREMENT COMMENT '编号',
    `account_id`           bigint       NOT NULL DEFAULT 0 COMMENT '公众号账号编号',
    `app_id`               varchar(64)  NOT NULL DEFAULT '' COMMENT '公众号 appId',
    `name`                 varchar(64)  NOT NULL DEFAULT '' COMMENT '菜单名称',
    `menu_key`             varchar(128)          DEFAULT '' COMMENT '菜单标识',
    `parent_id`            bigint       NOT NULL DEFAULT 0 COMMENT '父菜单编号',
    `type`                 varchar(32)           DEFAULT '' COMMENT '按钮类型',
    `url`                  varchar(512)          DEFAULT '' COMMENT '网页链接',
    `mini_program_app_id`  varchar(64)           DEFAULT '' COMMENT '小程序 appId',
    `mini_program_page_path` varchar(256)        DEFAULT '' COMMENT '小程序页面路径',
    `article_id`           varchar(64)           DEFAULT '' COMMENT '跳转图文媒体编号',
    `reply_message_type`   varchar(32)           DEFAULT '' COMMENT '回复消息类型',
    `reply_content`        varchar(2048)         DEFAULT '' COMMENT '回复消息内容',
    `reply_media_id`       varchar(128)          DEFAULT '' COMMENT '回复媒体 id',
    `reply_media_url`      varchar(512)          DEFAULT '' COMMENT '回复媒体 URL',
    `reply_title`          varchar(256)          DEFAULT '' COMMENT '回复标题',
    `reply_description`    varchar(512)          DEFAULT '' COMMENT '回复描述',
    `reply_thumb_media_id` varchar(128)          DEFAULT '' COMMENT '回复缩略图媒体 id',
    `reply_thumb_media_url` varchar(512)         DEFAULT '' COMMENT '回复缩略图 URL',
    `reply_articles`       json                  DEFAULT NULL COMMENT '回复图文消息数组',
    `reply_music_url`      varchar(512)          DEFAULT '' COMMENT '回复音乐链接',
    `reply_hq_music_url`   varchar(512)          DEFAULT '' COMMENT '回复高质量音乐链接',
    `creator`              varchar(64)           DEFAULT '' COMMENT '创建者',
    `create_time`          datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater`              varchar(64)           DEFAULT '' COMMENT '更新者',
    `update_time`          datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted`              bit(1)       NOT NULL DEFAULT 0 COMMENT '是否删除',
    PRIMARY KEY (`id`)
) ENGINE = InnoDB COMMENT = '公众号菜单';

CREATE TABLE IF NOT EXISTS `mp_auto_reply` (
    `id`                    bigint       NOT NULL AUTO_INCREMENT COMMENT '主键',
    `account_id`            bigint       NOT NULL DEFAULT 0 COMMENT '公众号账号编号',
    `app_id`                varchar(64)  NOT NULL DEFAULT '' COMMENT '公众号 appId',
    `type`                  tinyint      NOT NULL DEFAULT 0 COMMENT '回复类型',
    `request_keyword`       varchar(128)          DEFAULT '' COMMENT '请求关键字',
    `request_match`         tinyint               DEFAULT NULL COMMENT '请求关键字匹配方式',
    `request_message_type`  varchar(32)           DEFAULT '' COMMENT '请求消息类型',
    `response_message_type` varchar(32)  NOT NULL DEFAULT '' COMMENT '回复消息类型',
    `response_content`      varchar(2048)         DEFAULT '' COMMENT '回复消息内容',
    `response_media_id`     varchar(128)          DEFAULT '' COMMENT '回复媒体 id',
    `response_media_url`    varchar(512)          DEFAULT '' COMMENT '回复媒体 URL',
    `response_title`        varchar(256)          DEFAULT '' COMMENT '回复标题',
    `response_description`  varchar(512)          DEFAULT '' COMMENT '回复描述',
    `response_thumb_media_id` varchar(128)        DEFAULT '' COMMENT '回复缩略图媒体 id',
    `response_thumb_media_url` varchar(512)       DEFAULT '' COMMENT '回复缩略图 URL',
    `response_articles`     json                  DEFAULT NULL COMMENT '回复图文消息数组',
    `response_music_url`    varchar(512)          DEFAULT '' COMMENT '回复音乐链接',
    `response_hq_music_url` varchar(512)          DEFAULT '' COMMENT '回复高质量音乐链接',
    `creator`               varchar(64)           DEFAULT '' COMMENT '创建者',
    `create_time`           datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater`               varchar(64)           DEFAULT '' COMMENT '更新者',
    `update_time`           datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted`               bit(1)       NOT NULL DEFAULT 0 COMMENT '是否删除',
    PRIMARY KEY (`id`)
) ENGINE = InnoDB COMMENT = '公众号消息自动回复';

CREATE TABLE IF NOT EXISTS `mp_message` (
    `id`              bigint       NOT NULL AUTO_INCREMENT COMMENT '主键',
    `msg_id`          bigint                DEFAULT NULL COMMENT '微信公众号消息 id',
    `account_id`      bigint       NOT NULL DEFAULT 0 COMMENT '公众号账号 ID',
    `app_id`          varchar(64)  NOT NULL DEFAULT '' COMMENT '公众号 appid',
    `user_id`         bigint       NOT NULL DEFAULT 0 COMMENT '公众号粉丝编号',
    `openid`          varchar(64)  NOT NULL DEFAULT '' COMMENT '公众号粉丝标识',
    `type`            varchar(32)  NOT NULL DEFAULT '' COMMENT '消息类型',
    `send_from`       tinyint      NOT NULL DEFAULT 0 COMMENT '消息来源',
    `content`         varchar(2048)         DEFAULT '' COMMENT '消息内容',
    `media_id`        varchar(128)          DEFAULT '' COMMENT '媒体文件编号',
    `media_url`       varchar(512)          DEFAULT '' COMMENT '媒体文件 URL',
    `recognition`     varchar(512)          DEFAULT '' COMMENT '语音识别文本',
    `format`          varchar(32)           DEFAULT '' COMMENT '语音格式',
    `title`           varchar(256)          DEFAULT '' COMMENT '标题',
    `description`     varchar(512)          DEFAULT '' COMMENT '描述',
    `thumb_media_id`  varchar(128)          DEFAULT '' COMMENT '缩略图媒体 id',
    `thumb_media_url` varchar(512)          DEFAULT '' COMMENT '缩略图媒体 URL',
    `url`             varchar(512)          DEFAULT '' COMMENT '链接',
    `location_x`      double                DEFAULT NULL COMMENT '地理位置维度',
    `location_y`      double                DEFAULT NULL COMMENT '地理位置经度',
    `scale`           double                DEFAULT NULL COMMENT '地图缩放大小',
    `label`           varchar(256)          DEFAULT '' COMMENT '详细地址',
    `articles`        json                  DEFAULT NULL COMMENT '图文消息数组',
    `music_url`       varchar(512)          DEFAULT '' COMMENT '音乐链接',
    `hq_music_url`    varchar(512)          DEFAULT '' COMMENT '高质量音乐链接',
    `event`           varchar(64)           DEFAULT '' COMMENT '事件类型',
    `event_key`       varchar(128)          DEFAULT '' COMMENT '事件 Key',
    `creator`         varchar(64)           DEFAULT '' COMMENT '创建者',
    `create_time`     datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater`         varchar(64)           DEFAULT '' COMMENT '更新者',
    `update_time`     datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted`         bit(1)       NOT NULL DEFAULT 0 COMMENT '是否删除',
    PRIMARY KEY (`id`)
) ENGINE = InnoDB COMMENT = '公众号消息';

CREATE TABLE IF NOT EXISTS `mp_message_template` (
    `id`               bigint       NOT NULL AUTO_INCREMENT COMMENT '主键',
    `account_id`       bigint       NOT NULL DEFAULT 0 COMMENT '公众号账号编号',
    `app_id`           varchar(64)  NOT NULL DEFAULT '' COMMENT '公众号 appId',
    `template_id`      varchar(128) NOT NULL DEFAULT '' COMMENT '公众号模板 ID',
    `title`            varchar(128) NOT NULL DEFAULT '' COMMENT '标题',
    `content`          varchar(2048)         DEFAULT '' COMMENT '模板内容',
    `example`          varchar(2048)         DEFAULT '' COMMENT '模板示例',
    `primary_industry` varchar(64)           DEFAULT '' COMMENT '一级行业',
    `deputy_industry`  varchar(64)           DEFAULT '' COMMENT '二级行业',
    `creator`          varchar(64)           DEFAULT '' COMMENT '创建者',
    `create_time`      datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater`          varchar(64)           DEFAULT '' COMMENT '更新者',
    `update_time`      datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted`          bit(1)       NOT NULL DEFAULT 0 COMMENT '是否删除',
    PRIMARY KEY (`id`)
) ENGINE = InnoDB COMMENT = '公众号模板消息';

CREATE TABLE IF NOT EXISTS `mp_material` (
    `id`           bigint       NOT NULL AUTO_INCREMENT COMMENT '主键',
    `account_id`   bigint       NOT NULL DEFAULT 0 COMMENT '公众号账号编号',
    `app_id`       varchar(64)  NOT NULL DEFAULT '' COMMENT '公众号 appId',
    `media_id`     varchar(128) NOT NULL DEFAULT '' COMMENT '公众号素材 id',
    `type`         varchar(32)  NOT NULL DEFAULT '' COMMENT '文件类型',
    `permanent`    bit(1)       NOT NULL DEFAULT 0 COMMENT '是否永久',
    `url`          varchar(512)          DEFAULT '' COMMENT '文件服务器 URL',
    `name`         varchar(256)          DEFAULT '' COMMENT '名字',
    `mp_url`       varchar(512)          DEFAULT '' COMMENT '公众号文件 URL',
    `title`        varchar(256)          DEFAULT '' COMMENT '视频素材标题',
    `introduction` varchar(512)          DEFAULT '' COMMENT '视频素材描述',
    `creator`      varchar(64)           DEFAULT '' COMMENT '创建者',
    `create_time`  datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater`      varchar(64)           DEFAULT '' COMMENT '更新者',
    `update_time`  datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted`      bit(1)       NOT NULL DEFAULT 0 COMMENT '是否删除',
    PRIMARY KEY (`id`)
) ENGINE = InnoDB COMMENT = '公众号素材';
