-- AI视频生成任务表
CREATE TABLE IF NOT EXISTS `video_task` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '任务编号',
  `merchant_id` bigint NOT NULL COMMENT '商户编号',
  `user_id` bigint NOT NULL COMMENT '用户编号',
  `title` varchar(256) NOT NULL COMMENT '视频标题',
  `description` text NOT NULL COMMENT '视频描述/文案',
  `image_urls` json NOT NULL COMMENT '图片URL列表',
  `bgm_url` varchar(512) DEFAULT NULL COMMENT '背景音乐URL',
  `tts_audio_url` varchar(512) DEFAULT NULL COMMENT 'TTS语音URL',
  `video_url` varchar(512) DEFAULT NULL COMMENT '生成的视频URL',
  `duration` int DEFAULT NULL COMMENT '视频时长（秒）',
  `status` tinyint NOT NULL DEFAULT 0 COMMENT '任务状态：0-待处理 1-生成中 2-已完成 3-失败',
  `fail_reason` varchar(512) DEFAULT NULL COMMENT '失败原因',
  `douyin_publish_status` tinyint NOT NULL DEFAULT 0 COMMENT '抖音发布状态：0-未发布 1-发布中 2-已发布 3-发布失败',
  `douyin_item_id` varchar(128) DEFAULT NULL COMMENT '抖音视频ID',
  `douyin_publish_time` datetime DEFAULT NULL COMMENT '抖音发布时间',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`),
  KEY `idx_merchant_id` (`merchant_id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_tenant_id` (`tenant_id`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI视频生成任务表';
